<?php

use Ghi\Domain\Core\Models\Obra;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class TransaccionesInterfazSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection("cadeco")->statement("SET IDENTITY_INSERT Contabilidad.int_transacciones_interfaz ON;
            SET IDENTITY_INSERT Contabilidad.int_transacciones_interfaz ON;
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	1	,'Póliza de Factura de Prestaciones');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	2	,'Póliza de Provisión de Pasivo de Insumos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	3	,'Póliza de Factura Solo Materiales');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	4	,'Póliza de Factura Solo de Servicios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	5	,'Póliza de Factura Solo de Herramienta y Equipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	6	,'Póliza de Factura de Materiales y Servicios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	7	,'Póliza de Factura de Materiales y Herramienta y Equipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	8	,'Póliza de Factura de Servicios y Herramienta y Equipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	9	,'Póliza de Factura de Materiales, Servicios y Herramienta y Equipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	10	,'Póliza de Factura de Anticipo Solo Materiales');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	11	,'Póliza de Factura de Anticipo Solo de Servicios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	12	,'Póliza de Factura de Anticipo Solo de Herramienta y Equipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	13	,'Póliza de Factura de Anticipo de Materiales y Servicios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	14	,'Póliza de Factura de Anticipo de Materiales y Herramienta y Equipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	15	,'Póliza de Factura de Anticipo de Servicios y Herramienta y Equipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	16	,'Póliza de Factura de Anticipo de Materiales, Servicios y Herramienta y Equipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	17	,'Póliza de Pago de Factura de Anticipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	18	,'Póliza de Pago de Factura');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	19	,'Póliza de Provisión de Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	20	,'Póliza de Factura de Estimación');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	21	,'Póliza de Factura de Anticipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	22	,'Poliza de Factura de Anticipo y Estimación');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	23	,'Póliza de Pago de Anticipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	24	,'Póliza de Pago de Factura de Estimación');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	25	,'Póliza de Pago de Anticipo y Factura de Estimación');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	26	,'Póliza de Factura de Varios (Gastos Varios)');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	27	,'Póliza de Factura de Varios (Materiales/Servicios)');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	28	,'Póliza de Factura de Varios (Gastos Varios y Materiales/Servicios)');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	29	,'Póliza de Pago de Factura de Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	30	,'Póliza de Provisión de Rayas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	31	,'Póliza de Factura de Lista de Raya');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	32	,'Póliza de Factura de Prestaciones y Lista de Raya');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	33	,'Póliza de Pago de Lista de Raya/Prestación');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	34	,'Póliza de Provisión de Rentas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	35	,'Póliza de Factura de Anticipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	36	,'Póliza de Factura de Partes de Uso');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	37	,'Póliza de Factura de Anticipo y Partes de Uso');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	38	,'Póliza de Pago de Anticipo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	39	,'Póliza de Pago de Partes de Uso');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	40	,'Póliza de Pago de Anticipo y Partes de Uso ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	41	,'Póliza de Pago a Cuenta No Aplicado');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	42	,'Póliza de Pago a Cuenta Aplicado');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	43	,'Póliza de Facturas de Insumos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	44	,'Póliza de Facturas de Rentas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	45	,'Póliza de Facturas de Rayas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	46	,'Póliza de Facturas de Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	47	,'Póliza de Facturas de Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	48	,'Póliza de Facturas de Insumos y Rentas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	49	,'Póliza de Facturas de Insumos y Rayas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	50	,'Póliza de Facturas de Insumos y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	51	,'Póliza de Facturas de Insumos Y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	52	,'Póliza de Facturas de Rentas y Rayas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	53	,'Póliza de Facturas de Rentas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	54	,'Póliza de Facturas de Rentas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	55	,'Póliza de Facturas de Rayas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	56	,'Póliza de Facturas de Rayas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	57	,'Póliza de Facturas de Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	58	,'Póliza de Facturas de Insumos, Rentas y Rayas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	59	,'Póliza de Facturas de Insumos, Rentas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	60	,'Póliza de Facturas de Insumos, Rentas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	61	,'Póliza de Facturas de Insumos, Rayas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	62	,'Póliza de Facturas de Insumos, Rayas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	63	,'Póliza de Facturas de Insumos, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	64	,'Póliza de Facturas de Rentas, Rayas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	65	,'Póliza de Facturas de Rentas, Rayas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	66	,'Póliza de Facturas de Rayas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	67	,'Póliza de Facturas de Rentas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	68	,'Póliza de Facturas de Insumos, Rentas, Rayas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	69	,'Póliza de Facturas de Insumos, Rentas, Rayas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	70	,'Póliza de Facturas de Insumos, Rayas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	71	,'Póliza de Facturas de Insumos, Rentas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	72	,'Póliza de Facturas de Rentas, Rayas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	73	,'Póliza de Insumos, Rentas, Rayas, Fac. de Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	74	,'Póliza de Pago de Facturas de Insumos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	75	,'Póliza de Pago de Facturas de Rentas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	76	,'Póliza de Pago de Facturas de Rayas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	77	,'Póliza de Pago de Facturas de Insumos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	78	,'Póliza de Pago de Facturas de Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	79	,'Póliza de Pago de Facturas de Insumos y Rentas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	80	,'Póliza de Pago de Facturas de Insumos y Rayas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	81	,'Póliza de Pago de Facturas de Insumos y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	82	,'Póliza de Pago de Facturas de Insumos Y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	83	,'Póliza de Pago de Facturas de Rentas y Rayas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	84	,'Póliza de Pago de Facturas de Rentas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	85	,'Póliza de Pago de Facturas de Rentas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	86	,'Póliza de Pago de Facturas de Rayas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	87	,'Póliza de Pago de Facturas de Rayas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	88	,'Póliza de Pago de Facturas de Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	89	,'Póliza de Pago de Facturas de Insumos, Rentas y Rayas');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	90	,'Póliza de Pago de Facturas de Insumos, Rentas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	91	,'Póliza de Pago de Facturas de Insumos, Rentas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	92	,'Póliza de Pago de Facturas de Insumos, Rayas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	93	,'Póliza de Pago de Facturas de Insumos, Rayas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	94	,'Póliza de Pago de Facturas de Insumos, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	95	,'Póliza de Pago de Facturas de Rentas, Rayas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	96	,'Póliza de Pago de Facturas de Rentas, Rayas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	97	,'Póliza de Pago de Facturas de Rayas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	98	,'Póliza de Pago de Facturas de Rentas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	99	,'Póliza de Pago de Facturas de Insumos, Rentas, Rayas y Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	100	,'Póliza de Pago de Facturas de Insumos, Rentas, Rayas y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	101	,'Póliza de Pago de Facturas de Insumos, Rayas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	102	,'Póliza de Pago de Facturas de Insumos, Rentas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	103	,'Póliza de Pago de Facturas de Rentas, Rayas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	104	,'Póliza de Pago de Facturas de Insumos, Rentas, Rayas, Varios y Subcontratos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	105	,'Póliza de Pago de Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	106	,'Póliza de Pago de Pago Varios por Pago de Lista de Raya');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	107	,'Póliza de Pago de Pago Varios por Anticipos y Destajos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	108	,'Póliza de Pago de Pago Varios por Gastos Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	109	,'Póliza de Pago de Pago Varios por Remplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	110	,'Póliza de Pago de Pago Varios por Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	111	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	112	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	113	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos, Reemplazo de Cheque y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	114	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	115	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Anticipos y Destajos, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	116	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	117	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos y Gastos Varios,');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	118	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos y Reemplazo de Cheque,');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	119	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	120	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Gastos Varios y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	121	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Gastos Varios y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	122	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Reemplazo de Cheque y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	123	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios y Reemplazo de Cheque ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	124	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	125	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos, Reemplazo de Cheque y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	126	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	127	,'Póliza de Pago de Pago Varios Por Anticipos y Destajos, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	128	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya y Anticipos y Destajos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	129	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya y Gastos Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	130	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	131	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	132	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Anticipos y Destajos, y Gastos Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	133	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Anticipos y Destajos y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	134	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Anticipos y Destajos y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	135	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Gastos Varios y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	136	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Gastos Varios y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	137	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Reemplazo de Cheque y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	138	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos y Gastos Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	139	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	140	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	141	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Gastos Varios y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	142	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Gastos Varios y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	143	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Reemplazo de Cheque y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	144	,'Póliza de Pago de Pago Varios Por Anticipos y Destajos, Gastos Varios y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	145	,'Póliza de Pago de Pago Varios Por Anticipos y Destajos, Gastos Varios y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	146	,'Póliza de Pago de Pago Varios Por Anticipos y Destajos, Reemplazo de Cheque y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	147	,'Póliza de Pago de Pago Varios Por Gastos Varios y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	148	,'Póliza de Pago de Pago Varios Por Gastos Varios y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	149	,'Póliza de Pago de Pago Varios Por Reemplazo de Cheque y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	150	,'Póliza de Pago de Pago Varios Por Gastos Varios y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	151	,'Póliza de Pago de Pago Varios Por Gastos Varios y Pago a Cuenta');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	152	,'Póliza de Pago de Pago Varios Por Anticipos y Destajos y Gastos Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	153	,'Póliza de Pago de Pago Varios Por Anticipos y Destajos y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	154	,'Póliza de Pago de Pago Varios Por Anticipos y Destajos y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	155	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya y Anticipos y Destajos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	156	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya y Gastos Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	157	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	158	,'Póliza de Pago de Pago Varios Por Pago de Lista de Raya y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	159	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y Pago a Cuenta ');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	160	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y Reemplazo de Cheque');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	161	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y Gastos Varios');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	162	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y  Anticipos y Destajos');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	163	,'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y Pago de Lista de Raya');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	164	,'Póliza de Pago de Insumos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	165	,'Póliza de Pago de Rentas y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	166	,'Póliza de Pago de Rayas y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	167	,'Póliza de Pago de Varios y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	168	,'Póliza de Pago de Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	169	,'Póliza de Pago de Insumos, Rentas y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	170	,'Póliza de Pago de Insumos, Rayas y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	171	,'Póliza de Pago de Insumos, Varios y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	172	,'Póliza de Pago de Insumos, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	173	,'Póliza de Pago de Rentas, Rayas y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	174	,'Póliza de Pago de Rentas, Varios y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	175	,'Póliza de Pago de Rentas, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	176	,'Póliza de Pago de Rayas, Varios y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	177	,'Póliza de Pago de Rayas, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	178	,'Póliza de Pago de Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	179	,'Póliza de Pago de Insumos, Rentas, Rayas y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	180	,'Póliza de Pago de Insumos, Rentas, Varios y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	181	,'Póliza de Pago de Insumos, Rentas, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	182	,'Póliza de Pago de Insumos, Rayas, Varios y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	183	,'Póliza de Pago de Insumos, Rayas, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	184	,'Póliza de Pago de Insumos, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	185	,'Póliza de Pago de Rentas, Rayas, Varios y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	186	,'Póliza de Pago de Rentas, Rayas, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	187	,'Póliza de Pago de Rentas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	188	,'Póliza de Pago de Rayas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	189	,'Póliza de Pago de Insumos, Rentas, Rayas, Varios y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	190	,'Póliza de Pago de Insumos, Rentas, Rayas, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	191	,'Póliza de Pago de Insumos, Rentas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	192	,'Póliza de Pago de Insumos, Rayas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	193	,'Póliza de Pago de Rentas, Rayas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	194	,'Póliza de Pago de Insumos, Rentas, Rayas,Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	389	,'Póliza de Entrada de Almacén');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	390	,'Póliza de Salida de Almacén');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	391	,'Póliza de Transferencia de Almacén');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	392	,'Póliza de Cancelación de Registro de Remisión');	
insert into Contabilidad.int_transacciones_interfaz(id_transaccion_interfaz, descripcion) values(	393	,'Póliza de Factura');	

            ");
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	1	,'descripcion' => 	'Póliza de Factura de Prestaciones',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	2	,'descripcion' => 	'Póliza de Provisión de Pasivo de Insumos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	3	,'descripcion' => 	'Póliza de Factura Solo Materiales',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	4	,'descripcion' => 	'Póliza de Factura Solo de Servicios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	5	,'descripcion' => 	'Póliza de Factura Solo de Herramienta y Equipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	6	,'descripcion' => 	'Póliza de Factura de Materiales y Servicios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	7	,'descripcion' => 	'Póliza de Factura de Materiales y Herramienta y Equipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	8	,'descripcion' => 	'Póliza de Factura de Servicios y Herramienta y Equipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	9	,'descripcion' => 	'Póliza de Factura de Materiales, Servicios y Herramienta y Equipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	10	,'descripcion' => 	'Póliza de Factura de Anticipo Solo Materiales',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	11	,'descripcion' => 	'Póliza de Factura de Anticipo Solo de Servicios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	12	,'descripcion' => 	'Póliza de Factura de Anticipo Solo de Herramienta y Equipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	13	,'descripcion' => 	'Póliza de Factura de Anticipo de Materiales y Servicios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	14	,'descripcion' => 	'Póliza de Factura de Anticipo de Materiales y Herramienta y Equipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	15	,'descripcion' => 	'Póliza de Factura de Anticipo de Servicios y Herramienta y Equipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	16	,'descripcion' => 	'Póliza de Factura de Anticipo de Materiales, Servicios y Herramienta y Equipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	17	,'descripcion' => 	'Póliza de Pago de Factura de Anticipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	18	,'descripcion' => 	'Póliza de Pago de Factura',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	19	,'descripcion' => 	'Póliza de Provisión de Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	20	,'descripcion' => 	'Póliza de Factura de Estimación',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	21	,'descripcion' => 	'Póliza de Factura de Anticipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	22	,'descripcion' => 	'Poliza de Factura de Anticipo y Estimación',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	23	,'descripcion' => 	'Póliza de Pago de Anticipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	24	,'descripcion' => 	'Póliza de Pago de Factura de Estimación',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	25	,'descripcion' => 	'Póliza de Pago de Anticipo y Factura de Estimación',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	26	,'descripcion' => 	'Póliza de Factura de Varios (Gastos Varios)',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	27	,'descripcion' => 	'Póliza de Factura de Varios (Materiales/Servicios)',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	28	,'descripcion' => 	'Póliza de Factura de Varios (Gastos Varios y Materiales/Servicios)',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	29	,'descripcion' => 	'Póliza de Pago de Factura de Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	30	,'descripcion' => 	'Póliza de Provisión de Rayas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	31	,'descripcion' => 	'Póliza de Factura de Lista de Raya',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	32	,'descripcion' => 	'Póliza de Factura de Prestaciones y Lista de Raya',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	33	,'descripcion' => 	'Póliza de Pago de Lista de Raya/Prestación',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	34	,'descripcion' => 	'Póliza de Provisión de Rentas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	35	,'descripcion' => 	'Póliza de Factura de Anticipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	36	,'descripcion' => 	'Póliza de Factura de Partes de Uso',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	37	,'descripcion' => 	'Póliza de Factura de Anticipo y Partes de Uso',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	38	,'descripcion' => 	'Póliza de Pago de Anticipo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	39	,'descripcion' => 	'Póliza de Pago de Partes de Uso',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	40	,'descripcion' => 	'Póliza de Pago de Anticipo y Partes de Uso ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	41	,'descripcion' => 	'Póliza de Pago a Cuenta No Aplicado',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	42	,'descripcion' => 	'Póliza de Pago a Cuenta Aplicado',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	43	,'descripcion' => 	'Póliza de Facturas de Insumos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	44	,'descripcion' => 	'Póliza de Facturas de Rentas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	45	,'descripcion' => 	'Póliza de Facturas de Rayas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	46	,'descripcion' => 	'Póliza de Facturas de Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	47	,'descripcion' => 	'Póliza de Facturas de Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	48	,'descripcion' => 	'Póliza de Facturas de Insumos y Rentas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	49	,'descripcion' => 	'Póliza de Facturas de Insumos y Rayas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	50	,'descripcion' => 	'Póliza de Facturas de Insumos y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	51	,'descripcion' => 	'Póliza de Facturas de Insumos Y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	52	,'descripcion' => 	'Póliza de Facturas de Rentas y Rayas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	53	,'descripcion' => 	'Póliza de Facturas de Rentas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	54	,'descripcion' => 	'Póliza de Facturas de Rentas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	55	,'descripcion' => 	'Póliza de Facturas de Rayas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	56	,'descripcion' => 	'Póliza de Facturas de Rayas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	57	,'descripcion' => 	'Póliza de Facturas de Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	58	,'descripcion' => 	'Póliza de Facturas de Insumos, Rentas y Rayas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	59	,'descripcion' => 	'Póliza de Facturas de Insumos, Rentas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	60	,'descripcion' => 	'Póliza de Facturas de Insumos, Rentas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	61	,'descripcion' => 	'Póliza de Facturas de Insumos, Rayas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	62	,'descripcion' => 	'Póliza de Facturas de Insumos, Rayas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	63	,'descripcion' => 	'Póliza de Facturas de Insumos, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	64	,'descripcion' => 	'Póliza de Facturas de Rentas, Rayas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	65	,'descripcion' => 	'Póliza de Facturas de Rentas, Rayas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	66	,'descripcion' => 	'Póliza de Facturas de Rayas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	67	,'descripcion' => 	'Póliza de Facturas de Rentas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	68	,'descripcion' => 	'Póliza de Facturas de Insumos, Rentas, Rayas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	69	,'descripcion' => 	'Póliza de Facturas de Insumos, Rentas, Rayas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	70	,'descripcion' => 	'Póliza de Facturas de Insumos, Rayas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	71	,'descripcion' => 	'Póliza de Facturas de Insumos, Rentas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	72	,'descripcion' => 	'Póliza de Facturas de Rentas, Rayas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	73	,'descripcion' => 	'Póliza de Insumos, Rentas, Rayas, Fac. de Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	74	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	75	,'descripcion' => 	'Póliza de Pago de Facturas de Rentas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	76	,'descripcion' => 	'Póliza de Pago de Facturas de Rayas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	77	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	78	,'descripcion' => 	'Póliza de Pago de Facturas de Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	79	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos y Rentas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	80	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos y Rayas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	81	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	82	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos Y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	83	,'descripcion' => 	'Póliza de Pago de Facturas de Rentas y Rayas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	84	,'descripcion' => 	'Póliza de Pago de Facturas de Rentas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	85	,'descripcion' => 	'Póliza de Pago de Facturas de Rentas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	86	,'descripcion' => 	'Póliza de Pago de Facturas de Rayas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	87	,'descripcion' => 	'Póliza de Pago de Facturas de Rayas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	88	,'descripcion' => 	'Póliza de Pago de Facturas de Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	89	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rentas y Rayas',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	90	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rentas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	91	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rentas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	92	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rayas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	93	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rayas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	94	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	95	,'descripcion' => 	'Póliza de Pago de Facturas de Rentas, Rayas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	96	,'descripcion' => 	'Póliza de Pago de Facturas de Rentas, Rayas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	97	,'descripcion' => 	'Póliza de Pago de Facturas de Rayas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	98	,'descripcion' => 	'Póliza de Pago de Facturas de Rentas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	99	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rentas, Rayas y Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	100	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rentas, Rayas y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	101	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rayas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	102	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rentas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	103	,'descripcion' => 	'Póliza de Pago de Facturas de Rentas, Rayas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	104	,'descripcion' => 	'Póliza de Pago de Facturas de Insumos, Rentas, Rayas, Varios y Subcontratos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	105	,'descripcion' => 	'Póliza de Pago de Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	106	,'descripcion' => 	'Póliza de Pago de Pago Varios por Pago de Lista de Raya',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	107	,'descripcion' => 	'Póliza de Pago de Pago Varios por Anticipos y Destajos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	108	,'descripcion' => 	'Póliza de Pago de Pago Varios por Gastos Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	109	,'descripcion' => 	'Póliza de Pago de Pago Varios por Remplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	110	,'descripcion' => 	'Póliza de Pago de Pago Varios por Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	111	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	112	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	113	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos, Reemplazo de Cheque y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	114	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	115	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Anticipos y Destajos, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	116	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	117	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos y Gastos Varios,',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	118	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos y Reemplazo de Cheque,',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	119	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Anticipos y Destajos y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	120	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Gastos Varios y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	121	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Gastos Varios y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	122	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya, Reemplazo de Cheque y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	123	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios y Reemplazo de Cheque ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	124	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos, Gastos Varios y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	125	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos, Reemplazo de Cheque y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	126	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	127	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Anticipos y Destajos, Gastos Varios, Reemplazo de Cheque y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	128	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya y Anticipos y Destajos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	129	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya y Gastos Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	130	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	131	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Pago de Lista de Raya y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	132	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Anticipos y Destajos, y Gastos Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	133	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Anticipos y Destajos y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	134	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Anticipos y Destajos y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	135	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Gastos Varios y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	136	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Gastos Varios y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	137	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo, Reemplazo de Cheque y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	138	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos y Gastos Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	139	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	140	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Anticipos y Destajos y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	141	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Gastos Varios y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	142	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Gastos Varios y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	143	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya, Reemplazo de Cheque y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	144	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Anticipos y Destajos, Gastos Varios y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	145	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Anticipos y Destajos, Gastos Varios y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	146	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Anticipos y Destajos, Reemplazo de Cheque y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	147	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Gastos Varios y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	148	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Gastos Varios y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	149	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reemplazo de Cheque y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	150	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Gastos Varios y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	151	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Gastos Varios y Pago a Cuenta',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	152	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Anticipos y Destajos y Gastos Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	153	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Anticipos y Destajos y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	154	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Anticipos y Destajos y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	155	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya y Anticipos y Destajos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	156	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya y Gastos Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	157	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	158	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Pago de Lista de Raya y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	159	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y Pago a Cuenta ',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	160	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y Reemplazo de Cheque',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	161	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y Gastos Varios',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	162	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y  Anticipos y Destajos',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	163	,'descripcion' => 	'Póliza de Pago de Pago Varios Por Reposición de Fondo Fijo y Pago de Lista de Raya',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	164	,'descripcion' => 	'Póliza de Pago de Insumos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	165	,'descripcion' => 	'Póliza de Pago de Rentas y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	166	,'descripcion' => 	'Póliza de Pago de Rayas y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	167	,'descripcion' => 	'Póliza de Pago de Varios y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	168	,'descripcion' => 	'Póliza de Pago de Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	169	,'descripcion' => 	'Póliza de Pago de Insumos, Rentas y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	170	,'descripcion' => 	'Póliza de Pago de Insumos, Rayas y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	171	,'descripcion' => 	'Póliza de Pago de Insumos, Varios y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	172	,'descripcion' => 	'Póliza de Pago de Insumos, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	173	,'descripcion' => 	'Póliza de Pago de Rentas, Rayas y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	174	,'descripcion' => 	'Póliza de Pago de Rentas, Varios y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	175	,'descripcion' => 	'Póliza de Pago de Rentas, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	176	,'descripcion' => 	'Póliza de Pago de Rayas, Varios y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	177	,'descripcion' => 	'Póliza de Pago de Rayas, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	178	,'descripcion' => 	'Póliza de Pago de Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	179	,'descripcion' => 	'Póliza de Pago de Insumos, Rentas, Rayas y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	180	,'descripcion' => 	'Póliza de Pago de Insumos, Rentas, Varios y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	181	,'descripcion' => 	'Póliza de Pago de Insumos, Rentas, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	182	,'descripcion' => 	'Póliza de Pago de Insumos, Rayas, Varios y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	183	,'descripcion' => 	'Póliza de Pago de Insumos, Rayas, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	184	,'descripcion' => 	'Póliza de Pago de Insumos, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	185	,'descripcion' => 	'Póliza de Pago de Rentas, Rayas, Varios y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	186	,'descripcion' => 	'Póliza de Pago de Rentas, Rayas, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	187	,'descripcion' => 	'Póliza de Pago de Rentas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	188	,'descripcion' => 	'Póliza de Pago de Rayas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	189	,'descripcion' => 	'Póliza de Pago de Insumos, Rentas, Rayas, Varios y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	190	,'descripcion' => 	'Póliza de Pago de Insumos, Rentas, Rayas, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	191	,'descripcion' => 	'Póliza de Pago de Insumos, Rentas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	192	,'descripcion' => 	'Póliza de Pago de Insumos, Rayas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	193	,'descripcion' => 	'Póliza de Pago de Rentas, Rayas, Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	194	,'descripcion' => 	'Póliza de Pago de Insumos, Rentas, Rayas,Varios, Subcontratos y Pago Varios por Reposición de Fondo Fijo',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	389	,'descripcion' => 	'Póliza de Entrada de Almacén',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	390	,'descripcion' => 	'Póliza de Salida de Almacén',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	391	,'descripcion' => 	'Póliza de Transferencia de Almacén',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	392	,'descripcion' => 	'Póliza de Cancelación de Registro de Remisión',]);
//        DB::connection("cadeco")->table('Contabilidad.int_transacciones_interfaz')->insert( ['id_transaccion_interfaz' =>	393	,'descripcion' => 	'Póliza de Factura',]);
//        //DB::statement('SET IDENTITY_INSERT dbo.int_transacciones_interfaz OFF;');
    }
}
